name: CI

on:
  push:
    branches:
      - publish

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Python and Extract ODM parameters
      run: |
        apt update -y
        apt install -y python build-essential
        make autogenerate
    - uses: ammaraskar/sphinx-action@master
      with:
        build-command: "make build"
        docs-folder: "source/"
    - name: Commit documentation changes
      run: |
        git clone https://github.com/OpenDroneMap/docs --branch gh-pages --single-branch gh-pages
        cp -r _build/html/* gh-pages/
        cd gh-pages
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update documentation" -a || true
        # The above command will fail if no changes were present, so we ignore
        # that.
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
